version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "18411:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      JWT_SECRET: 78b37db2f09767c7ad3eb47c903739359c69aa57080c2710db92fcb1809f8cd4
    ports:
      - "18412:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18413:90"
    depends_on:
      - backend

volumes:
  postgres_data:
